{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter-engine",
    "version": "5.9.0-M1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.9.0-M1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-engine",
          "version": {
            "requires": "1.9.0-M1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.9.0-M1"
          }
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-engine-5.9.0-M1.jar",
          "url": "junit-jupiter-engine-5.9.0-M1.jar",
          "size": 238389,
          "sha512": "dd355810d736b0ff4a2930a97790c3fc76dadd135f233e163c71a121762a210b4d202c64feca1913851225901ae1c69d7b6f9fc30165b1a6fe1f4ce58825bb42",
          "sha256": "6447376c4f0bc8382309e597704e9bbf91c459aa2bada4425c947601002a216c",
          "sha1": "88c3cf175d17fbaa874257b6c4a3c2d2d453fe44",
          "md5": "8c53f835e90648db0198a76747b7ccd3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.9.0-M1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-engine",
          "version": {
            "requires": "1.9.0-M1"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.9.0-M1"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-engine-5.9.0-M1.jar",
          "url": "junit-jupiter-engine-5.9.0-M1.jar",
          "size": 238389,
          "sha512": "dd355810d736b0ff4a2930a97790c3fc76dadd135f233e163c71a121762a210b4d202c64feca1913851225901ae1c69d7b6f9fc30165b1a6fe1f4ce58825bb42",
          "sha256": "6447376c4f0bc8382309e597704e9bbf91c459aa2bada4425c947601002a216c",
          "sha1": "88c3cf175d17fbaa874257b6c4a3c2d2d453fe44",
          "md5": "8c53f835e90648db0198a76747b7ccd3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-engine-5.9.0-M1-javadoc.jar",
          "url": "junit-jupiter-engine-5.9.0-M1-javadoc.jar",
          "size": 408441,
          "sha512": "737fd5b21ef86c6d06e18d01cce87b8a4b06364988f9581a23e219147d5a67e0f43335e3110d3c02dcd0a208c9ad2f60c19b63971c4646040320052658a43f6f",
          "sha256": "1cc50f8b14154a359f3688af27f01b9836935c80a0e3fdad48cc239bb1dabcde",
          "sha1": "186f70780c2a0db48062535f92efbcd86abf40ed",
          "md5": "1d624f8ff1bff08670819af7961f0b84"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-engine-5.9.0-M1-sources.jar",
          "url": "junit-jupiter-engine-5.9.0-M1-sources.jar",
          "size": 127237,
          "sha512": "97f7a72cf82a960292e41cc9bebde1e11678bb48c3ad2abaeb9cd34c3df85ae1cfe35de3df86dc8ce39dbb49552888d2acec0f96873e8a870ad34c6052b7459a",
          "sha256": "848100f90ab66e3c0090695581011af26495ecbb77ff6d0b0e642bc9a0a33673",
          "sha1": "8a0d703aae7fe13c16b3fa297e7e709f8a7232fc",
          "md5": "e86fa422b4e21859160c2ceda4d84f4b"
        }
      ]
    }
  ]
}
