{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.jupiter",
    "module": "junit-jupiter-api",
    "version": "5.9.0-M1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.9.0-M1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "1.9.0-M1"
          }
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-api-5.9.0-M1.jar",
          "url": "junit-jupiter-api-5.9.0-M1.jar",
          "size": 197255,
          "sha512": "7c0e1acc6d9dc86d7650242c754554d740e7347efea4e824cccded7bf0f3287f7e9516e3fdc64be73d0b7aa7e6ef1d73e170423ee514bc1d94fc624c88248a95",
          "sha256": "941bd0870866a143a0773b2876c373350979576bcae174b35f874d7c93fe385e",
          "sha1": "9fc0f98b087588118277c53667333bcd7811aa5c",
          "md5": "cd6482ab486c9a0273870330f4468026"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.9.0-M1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.opentest4j",
          "module": "opentest4j",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-commons",
          "version": {
            "requires": "1.9.0-M1"
          }
        }
      ],
      "files": [
        {
          "name": "junit-jupiter-api-5.9.0-M1.jar",
          "url": "junit-jupiter-api-5.9.0-M1.jar",
          "size": 197255,
          "sha512": "7c0e1acc6d9dc86d7650242c754554d740e7347efea4e824cccded7bf0f3287f7e9516e3fdc64be73d0b7aa7e6ef1d73e170423ee514bc1d94fc624c88248a95",
          "sha256": "941bd0870866a143a0773b2876c373350979576bcae174b35f874d7c93fe385e",
          "sha1": "9fc0f98b087588118277c53667333bcd7811aa5c",
          "md5": "cd6482ab486c9a0273870330f4468026"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-api-5.9.0-M1-javadoc.jar",
          "url": "junit-jupiter-api-5.9.0-M1-javadoc.jar",
          "size": 767510,
          "sha512": "6f62cbb2718f6d6fd851de2423e5e8e31a3139f4f6c9e7411935b739640125c5b15e27ec70a8c7f29838016b9d89224809565f4c115c1f730fef92e82190321f",
          "sha256": "2ccda58bf265f212c9c3e6c051b0db80efe7ebfc3e3a7a61d960fc57c792bdd8",
          "sha1": "5484ee36274b086d96816d8cfb5a8c8fb0c85ecf",
          "md5": "85dd74a3ad27211f031e0b28ee1b6da5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-jupiter-api-5.9.0-M1-sources.jar",
          "url": "junit-jupiter-api-5.9.0-M1-sources.jar",
          "size": 193886,
          "sha512": "46b2f84b05256a16389bd9be996852cbfe5d873fc30428616d9b6729eb9e1d80dd7d48be0f7df485fe6ebfed7a9fb0724ea36452a067e77115e6889533fc5d69",
          "sha256": "83fb90b23fe043dae984acb84ee701fba64cef209848fcbae7b2c640d8fd43e2",
          "sha1": "88a8b64fd34b028926209b0f36b46cc661cbdaee",
          "md5": "f61c9aa386b0d2a1352f377f0b553967"
        }
      ]
    }
  ]
}
